"""Constants for the GRIT Hub integration."""
from __future__ import annotations

DOMAIN = "grit_hub"
DEFAULT_NAME = "GRIT Hub"
DEFAULT_MQTT_PORT = 1883
DEFAULT_MQTT_KEEPALIVE = 60

MAX_MQTT_HOST_LENGTH = 253
MAX_MQTT_HUB_ID_LENGTH = 128
MAX_MQTT_USERNAME_LENGTH = 128
MQTT_READY_TIMEOUT = 15.0
DEFAULT_SCAN_INTERVAL = 30

CONF_BASE_URL = "base_url"
CONF_TOKEN = "token"
CONF_VERIFY_SSL = "verify_ssl"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_MQTT_HOST = "mqtt_host"
CONF_MQTT_PORT = "mqtt_port"
CONF_MQTT_HUB_ID = "mqtt_hub_id"
CONF_MQTT_USERNAME = "mqtt_username"
CONF_MQTT_PASSWORD = "mqtt_password"
CONF_MQTT_USE_TLS = "mqtt_use_tls"
CONF_MQTT_VERIFY_TLS = "mqtt_verify_tls"
CONF_MQTT_KEEPALIVE = "mqtt_keepalive"

PLATFORMS = ["sensor", "binary_sensor", "switch", "cover", "button"]

# Device collections discovered by the API. The integration will create entities
# when the corresponding endpoint returns a list of device objects.
DEVICE_TYPES = [
    "rfid",
    "solenoid",
    "latch",
    "collector",
    "powerbank",
    "gate",
    "airquality",
    "dustbin",
    "magswipe",
    "presence",
    "pressure",
    "scanner",
    "trigger",
    "xtndr",
]

SWITCH_DEVICE_TYPES = ["rfid", "solenoid", "latch", "collector", "powerbank"]
COVER_DEVICE_TYPES = ["gate"]
SENSOR_DEVICE_TYPES = ["airquality", "presence", "pressure", "dustbin", "magswipe", "scanner", "trigger", "xtndr"]

# Imported/generated from the source Swagger/OpenAPI catalogue. It is retained
# for reference only and is not exposed through a general endpoint service.
ENDPOINTS = [
    {"method": "DELETE", "path": "/api/airquality/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/asset/image/{id}"},
    {"method": "DELETE", "path": "/api/collector/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/device/mesh-telemetry"},
    {"method": "DELETE", "path": "/api/device/mesh-telemetry/{deviceId}"},
    {"method": "DELETE", "path": "/api/dustbin/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/gate/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/grit-track/access-time/{id}"},
    {"method": "DELETE", "path": "/api/grit-track/job-code/{id}"},
    {"method": "DELETE", "path": "/api/grit-track/permission-group/{id}"},
    {"method": "DELETE", "path": "/api/grit-track/timecard/{id}"},
    {"method": "DELETE", "path": "/api/grit-track/user/{id}"},
    {"method": "DELETE", "path": "/api/hub/cloud-connect"},
    {"method": "DELETE", "path": "/api/hub/delete-offline-new-devices"},
    {"method": "DELETE", "path": "/api/hub/image/{type}"},
    {"method": "DELETE", "path": "/api/hub/token/{id}"},
    {"method": "DELETE", "path": "/api/import/{id}"},
    {"method": "DELETE", "path": "/api/integration/{key}/delete"},
    {"method": "DELETE", "path": "/api/latch/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/magswipe/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/maintenance/{id}"},
    {"method": "DELETE", "path": "/api/notification/{id}"},
    {"method": "DELETE", "path": "/api/powerbank/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/presence/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/pressure/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/resource/{id}"},
    {"method": "DELETE", "path": "/api/rfid/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/scanner/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/solenoid/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/trigger/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/wallet/image/{type}"},
    {"method": "DELETE", "path": "/api/wallet/{mobileDeviceId}/unregister/{userId}/{cardId}"},
    {"method": "DELETE", "path": "/api/wallet/{userId}/{cardId}"},
    {"method": "DELETE", "path": "/api/wiegand-format/{id}"},
    {"method": "DELETE", "path": "/api/wireguard/client/{name}"},
    {"method": "DELETE", "path": "/api/xtndr/{id}/{replacementId}"},
    {"method": "DELETE", "path": "/api/zerotier/{id}"},
    {"method": "GET", "path": "/"},
    {"method": "GET", "path": "/api/airquality"},
    {"method": "GET", "path": "/api/airquality/{id}"},
    {"method": "GET", "path": "/api/airquality/{id}/historical"},
    {"method": "GET", "path": "/api/asset/checkout"},
    {"method": "GET", "path": "/api/asset/filter-options"},
    {"method": "GET", "path": "/api/asset/location-hierarchy"},
    {"method": "GET", "path": "/api/asset/media/{type}/{keyword}"},
    {"method": "GET", "path": "/api/asset/paginated"},
    {"method": "GET", "path": "/api/asset/picklists"},
    {"method": "GET", "path": "/api/asset/templates"},
    {"method": "GET", "path": "/api/asset/{id}"},
    {"method": "GET", "path": "/api/collector"},
    {"method": "GET", "path": "/api/collector/{id}"},
    {"method": "GET", "path": "/api/device/adoption-requests"},
    {"method": "GET", "path": "/api/device/locate/{type}/{id}"},
    {"method": "GET", "path": "/api/device/mesh-telemetry"},
    {"method": "GET", "path": "/api/device/refresh/{type}/{id}"},
    {"method": "GET", "path": "/api/dustbin"},
    {"method": "GET", "path": "/api/dustbin/{id}"},
    {"method": "GET", "path": "/api/firmware/check/{filename}"},
    {"method": "GET", "path": "/api/firmware/download/{filename}"},
    {"method": "GET", "path": "/api/firmware/latest/{partialName}"},
    {"method": "GET", "path": "/api/firmware/list/{chipType}/{deviceId}"},
    {"method": "GET", "path": "/api/firmware/{filename}/meta"},
    {"method": "GET", "path": "/api/gate"},
    {"method": "GET", "path": "/api/gate/{id}"},
    {"method": "GET", "path": "/api/grit-track"},
    {"method": "GET", "path": "/api/grit-track/access-time"},
    {"method": "GET", "path": "/api/grit-track/demographics/{includeAssociations}"},
    {"method": "GET", "path": "/api/grit-track/job-code"},
    {"method": "GET", "path": "/api/grit-track/permission-group"},
    {"method": "GET", "path": "/api/grit-track/permission-group/{id}/user"},
    {"method": "GET", "path": "/api/grit-track/timecard/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/grit-track/timecard/{userid}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/grit-track/user"},
    {"method": "GET", "path": "/api/grit-track/user-agreement"},
    {"method": "GET", "path": "/api/grit-track/user/{id}/active-timecard"},
    {"method": "GET", "path": "/api/grit-track/user/{id}/user-agreement"},
    {"method": "GET", "path": "/api/grit-track/verify/{token}"},
    {"method": "GET", "path": "/api/hub/backup"},
    {"method": "GET", "path": "/api/hub/backup-status"},
    {"method": "GET", "path": "/api/hub/cloud-settings"},
    {"method": "GET", "path": "/api/hub/country"},
    {"method": "GET", "path": "/api/hub/gateway-duplicate-history"},
    {"method": "GET", "path": "/api/hub/gateway-duplicate-stats"},
    {"method": "GET", "path": "/api/hub/gateway-queue-messages"},
    {"method": "GET", "path": "/api/hub/token"},
    {"method": "GET", "path": "/api/hub/{id}"},
    {"method": "GET", "path": "/api/import/details/{id}"},
    {"method": "GET", "path": "/api/import/download/{id}"},
    {"method": "GET", "path": "/api/import/{entity}"},
    {"method": "GET", "path": "/api/import/{entity}/export"},
    {"method": "GET", "path": "/api/import/{entity}/fields"},
    {"method": "GET", "path": "/api/import/{id}/errors"},
    {"method": "GET", "path": "/api/integration"},
    {"method": "GET", "path": "/api/integration/{key}/data"},
    {"method": "GET", "path": "/api/latch"},
    {"method": "GET", "path": "/api/latch/{id}"},
    {"method": "GET", "path": "/api/magswipe"},
    {"method": "GET", "path": "/api/magswipe/{id}"},
    {"method": "GET", "path": "/api/maintenance"},
    {"method": "GET", "path": "/api/maintenance/{deviceType}/{id}"},
    {"method": "GET", "path": "/api/maintenance/{id}"},
    {"method": "GET", "path": "/api/notification"},
    {"method": "GET", "path": "/api/powerbank"},
    {"method": "GET", "path": "/api/powerbank/{id}"},
    {"method": "GET", "path": "/api/presence"},
    {"method": "GET", "path": "/api/presence/{id}"},
    {"method": "GET", "path": "/api/pressure"},
    {"method": "GET", "path": "/api/pressure/{id}"},
    {"method": "GET", "path": "/api/pressure/{id}/history/{date}"},
    {"method": "GET", "path": "/api/report/activity/{dateRange}/{filter}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset-status/lifecycle/{assetId}/{dateRange}"},
    {"method": "GET", "path": "/api/report/asset-status/overdue/{dateRange}"},
    {"method": "GET", "path": "/api/report/asset-status/overview/{dateRange}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset-status/performance/{dateRange}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset-status/user-behavior/{dateRange}/{userId}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset-status/utilization/{dateRange}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset/{dateRange}/user/{userId}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/asset/{dateRange}/{id}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/maintenance/{dateRange}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/metrics/recent"},
    {"method": "GET", "path": "/api/report/metrics/{metricType}/{dateRange}/{devices}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/permission/{groupBy}/{id}"},
    {"method": "GET", "path": "/api/report/timecard/{dateRange}/{userId}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/trigger/{id}/{key}/{dateRange}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/usage/{key}/{dateRange}/{dataset}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/report/user/{id}/{key}/{dateRange}/{demographic}/{startDate}/{endDate}"},
    {"method": "GET", "path": "/api/resource"},
    {"method": "GET", "path": "/api/resource/{type}"},
    {"method": "GET", "path": "/api/rfid"},
    {"method": "GET", "path": "/api/rfid/{id}"},
    {"method": "GET", "path": "/api/scanner"},
    {"method": "GET", "path": "/api/scanner/{id}"},
    {"method": "GET", "path": "/api/solenoid"},
    {"method": "GET", "path": "/api/solenoid/{id}"},
    {"method": "GET", "path": "/api/sse/data"},
    {"method": "GET", "path": "/api/sse/stats"},
    {"method": "GET", "path": "/api/sse/subscribe"},
    {"method": "GET", "path": "/api/telemetry/anomalies"},
    {"method": "GET", "path": "/api/telemetry/devices"},
    {"method": "GET", "path": "/api/telemetry/devices-windowed"},
    {"method": "GET", "path": "/api/telemetry/devices/{deviceId}"},
    {"method": "GET", "path": "/api/telemetry/devices/{deviceId}/history"},
    {"method": "GET", "path": "/api/telemetry/topology"},
    {"method": "GET", "path": "/api/tracker/asset/{id}"},
    {"method": "GET", "path": "/api/tracker/search"},
    {"method": "GET", "path": "/api/tracker/user/{id}"},
    {"method": "GET", "path": "/api/trigger"},
    {"method": "GET", "path": "/api/trigger/{id}"},
    {"method": "GET", "path": "/api/update/hub"},
    {"method": "GET", "path": "/api/update/status"},
    {"method": "GET", "path": "/api/wallet/{mobileDeviceId}"},
    {"method": "GET", "path": "/api/wallet/{type}/link/{userId}"},
    {"method": "GET", "path": "/api/wallet/{type}/pass/{userId}"},
    {"method": "GET", "path": "/api/wallet/{type}/{userId}/{cardId}"},
    {"method": "GET", "path": "/api/wiegand-format"},
    {"method": "GET", "path": "/api/wiegand-format/{id}"},
    {"method": "GET", "path": "/api/wifi-network"},
    {"method": "GET", "path": "/api/wireguard"},
    {"method": "GET", "path": "/api/wireguard/client/{name}"},
    {"method": "GET", "path": "/api/wireguard/client/{name}/configuration"},
    {"method": "GET", "path": "/api/wireguard/client/{name}/{width}/qrcode.svg"},
    {"method": "GET", "path": "/api/xtndr"},
    {"method": "GET", "path": "/api/xtndr/{id}"},
    {"method": "GET", "path": "/api/zerotier"},
    {"method": "GET", "path": "/api/zerotier/{id}"},
    {"method": "GET", "path": "/email-failure-verification"},
    {"method": "GET", "path": "/email-success-verification"},
    {"method": "GET", "path": "/health-check"},
    {"method": "GET", "path": "/login"},
    {"method": "GET", "path": "/password-reset/{token}"},
    {"method": "GET", "path": "/phone-failure-verification"},
    {"method": "GET", "path": "/phone-success-verification"},
    {"method": "GET", "path": "/signon"},
    {"method": "GET", "path": "/sso/login"},
    {"method": "GET", "path": "/sso/metadata"},
    {"method": "GET", "path": "/tracker"},
    {"method": "GET", "path": "/wallet"},
    {"method": "POST", "path": "/api/airquality/{id}/override/{enable}"},
    {"method": "POST", "path": "/api/asset/{id}/image"},
    {"method": "POST", "path": "/api/command/{deviceType}/{id}/modbus/{command}/{address}/{value}"},
    {"method": "POST", "path": "/api/command/{deviceType}/{id}/{commandName}/{action}/{remoteType}"},
    {"method": "POST", "path": "/api/device/mesh-telemetry/refresh"},
    {"method": "POST", "path": "/api/device/mesh-telemetry/refresh/{type}/{id}"},
    {"method": "POST", "path": "/api/grit-track/access-time"},
    {"method": "POST", "path": "/api/grit-track/job-code"},
    {"method": "POST", "path": "/api/grit-track/permission-group"},
    {"method": "POST", "path": "/api/grit-track/reset-user-agreements"},
    {"method": "POST", "path": "/api/grit-track/timecard/{userid}"},
    {"method": "POST", "path": "/api/grit-track/user"},
    {"method": "POST", "path": "/api/grit-track/user/{id}/signed-user-agreement"},
    {"method": "POST", "path": "/api/hub/adopt/{deviceType}/{deviceId}"},
    {"method": "POST", "path": "/api/hub/backup/{type}"},
    {"method": "POST", "path": "/api/hub/clear-cache"},
    {"method": "POST", "path": "/api/hub/cloud-connect"},
    {"method": "POST", "path": "/api/hub/email-test"},
    {"method": "POST", "path": "/api/hub/gateway-metrics-refresh"},
    {"method": "POST", "path": "/api/hub/image/{type}"},
    {"method": "POST", "path": "/api/hub/inform-mesh"},
    {"method": "POST", "path": "/api/hub/logger/{deviceId}"},
    {"method": "POST", "path": "/api/hub/mqtt/publish"},
    {"method": "POST", "path": "/api/hub/restore"},
    {"method": "POST", "path": "/api/hub/sms-test"},
    {"method": "POST", "path": "/api/hub/ssh/{enable}"},
    {"method": "POST", "path": "/api/hub/tunnel/{enable}"},
    {"method": "POST", "path": "/api/import/{entity}"},
    {"method": "POST", "path": "/api/import/{entity}/available-configurations"},
    {"method": "POST", "path": "/api/import/{entity}/export"},
    {"method": "POST", "path": "/api/integration/{key}/execute"},
    {"method": "POST", "path": "/api/magswipe/rapid-signout/{id}/{enable}"},
    {"method": "POST", "path": "/api/maintenance/{deviceId}"},
    {"method": "POST", "path": "/api/maintenance/{id}/activity"},
    {"method": "POST", "path": "/api/notification"},
    {"method": "POST", "path": "/api/resource"},
    {"method": "POST", "path": "/api/rfid/{id}/lockout"},
    {"method": "POST", "path": "/api/sdr/start"},
    {"method": "POST", "path": "/api/sdr/stop"},
    {"method": "POST", "path": "/api/sse/journal/subscribe"},
    {"method": "POST", "path": "/api/sse/journal/unsubscribe"},
    {"method": "POST", "path": "/api/sse/test-message"},
    {"method": "POST", "path": "/api/telemetry/anomalies/acknowledge-bulk"},
    {"method": "POST", "path": "/api/telemetry/anomalies/{id}/acknowledge"},
    {"method": "POST", "path": "/api/telemetry/anomalies/{id}/resolve"},
    {"method": "POST", "path": "/api/tracker/authenticate"},
    {"method": "POST", "path": "/api/tracker/checkin/{id}"},
    {"method": "POST", "path": "/api/tracker/checkout"},
    {"method": "POST", "path": "/api/tracker/damaged/{id}"},
    {"method": "POST", "path": "/api/update/cancel/{deviceType}/{deviceId}"},
    {"method": "POST", "path": "/api/update/{deviceType}"},
    {"method": "POST", "path": "/api/wallet/email/{userId}"},
    {"method": "POST", "path": "/api/wallet/image/{type}"},
    {"method": "POST", "path": "/api/wallet/{mobileDeviceId}/register/{userId}/{cardId}"},
    {"method": "POST", "path": "/api/wiegand-format"},
    {"method": "POST", "path": "/api/wiegand-format/capture/{start}"},
    {"method": "POST", "path": "/api/wiegand-format/test/{start}"},
    {"method": "POST", "path": "/api/wifi-network/connect"},
    {"method": "POST", "path": "/api/wifi-network/disconnect"},
    {"method": "POST", "path": "/api/wifi-network/mode/{mode}"},
    {"method": "POST", "path": "/api/wifi-network/save"},
    {"method": "POST", "path": "/api/wireguard/client/{name}/email"},
    {"method": "POST", "path": "/api/wireguard/{id}/client/{name}"},
    {"method": "POST", "path": "/api/xtndr/{id}/inform-mesh"},
    {"method": "POST", "path": "/api/zerotier/{id}"},
    {"method": "POST", "path": "/api/zerotier/{id}/email"},
    {"method": "POST", "path": "/create-account"},
    {"method": "POST", "path": "/forgot-password"},
    {"method": "POST", "path": "/forgot-pin"},
    {"method": "POST", "path": "/login"},
    {"method": "POST", "path": "/logout"},
    {"method": "POST", "path": "/password-reset"},
    {"method": "POST", "path": "/sso/login/callback"},
    {"method": "PUT", "path": "/api/airquality/{id}"},
    {"method": "PUT", "path": "/api/airquality/{id}/realtimemeasurement/{enabled}"},
    {"method": "PUT", "path": "/api/airquality/{id}/trigger/{triggerId}"},
    {"method": "PUT", "path": "/api/asset/{id}"},
    {"method": "PUT", "path": "/api/asset/{id}/status"},
    {"method": "PUT", "path": "/api/collector/{id}"},
    {"method": "PUT", "path": "/api/collector/{id}/realtimepower/{enabled}"},
    {"method": "PUT", "path": "/api/collector/{id}/state/{onOff}"},
    {"method": "PUT", "path": "/api/collector/{id}/trigger/{triggerId}"},
    {"method": "PUT", "path": "/api/collector/{id}/vfd"},
    {"method": "PUT", "path": "/api/collector/{id}/vfd/{frequencyChange}"},
    {"method": "PUT", "path": "/api/command/{deviceType}/{id}/{commandName}/{action}/{remoteType}"},
    {"method": "PUT", "path": "/api/device/group/{type}/{id}"},
    {"method": "PUT", "path": "/api/device/mesh-repeater/{id}/{value}"},
    {"method": "PUT", "path": "/api/device/tx-power/{id}/{value}"},
    {"method": "PUT", "path": "/api/dustbin/{id}"},
    {"method": "PUT", "path": "/api/gate/{id}"},
    {"method": "PUT", "path": "/api/gate/{id}/calibrate"},
    {"method": "PUT", "path": "/api/gate/{id}/center"},
    {"method": "PUT", "path": "/api/gate/{id}/move"},
    {"method": "PUT", "path": "/api/gate/{id}/offset"},
    {"method": "PUT", "path": "/api/gate/{id}/realtimemeasurement/{enabled}"},
    {"method": "PUT", "path": "/api/gate/{id}/reboot"},
    {"method": "PUT", "path": "/api/gate/{id}/state/{open}"},
    {"method": "PUT", "path": "/api/gate/{id}/trigger/{triggerId}"},
    {"method": "PUT", "path": "/api/grit-track/access-time/{id}"},
    {"method": "PUT", "path": "/api/grit-track/job-code/{id}"},
    {"method": "PUT", "path": "/api/grit-track/permission-group/{id}"},
    {"method": "PUT", "path": "/api/grit-track/timecard/{id}"},
    {"method": "PUT", "path": "/api/grit-track/user-agreement"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/active"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/external-id"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/external-proximity-card"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/password"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/signin"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/signout"},
    {"method": "PUT", "path": "/api/grit-track/user/{id}/verify"},
    {"method": "PUT", "path": "/api/hub/cloud-connect"},
    {"method": "PUT", "path": "/api/hub/cloud-settings"},
    {"method": "PUT", "path": "/api/hub/image/{type}"},
    {"method": "PUT", "path": "/api/hub/ip-settings"},
    {"method": "PUT", "path": "/api/hub/lockout/{id}"},
    {"method": "PUT", "path": "/api/hub/reboot"},
    {"method": "PUT", "path": "/api/hub/restart"},
    {"method": "PUT", "path": "/api/hub/settime"},
    {"method": "PUT", "path": "/api/hub/shutdown"},
    {"method": "PUT", "path": "/api/hub/token"},
    {"method": "PUT", "path": "/api/hub/{id}"},
    {"method": "PUT", "path": "/api/hub/{id}/settings"},
    {"method": "PUT", "path": "/api/import/{id}/configure"},
    {"method": "PUT", "path": "/api/import/{id}/{action}"},
    {"method": "PUT", "path": "/api/integration/{key}/save"},
    {"method": "PUT", "path": "/api/latch/{id}"},
    {"method": "PUT", "path": "/api/latch/{id}/state/{onOff}"},
    {"method": "PUT", "path": "/api/magswipe/{id}"},
    {"method": "PUT", "path": "/api/magswipe/{id}/mode/{mode}"},
    {"method": "PUT", "path": "/api/maintenance/{id}"},
    {"method": "PUT", "path": "/api/notification/{id}"},
    {"method": "PUT", "path": "/api/powerbank/{id}"},
    {"method": "PUT", "path": "/api/powerbank/{id}/realtimepower/{enabled}"},
    {"method": "PUT", "path": "/api/powerbank/{id}/state/{onOff}"},
    {"method": "PUT", "path": "/api/presence/{id}"},
    {"method": "PUT", "path": "/api/pressure/{id}"},
    {"method": "PUT", "path": "/api/pressure/{id}/realtimemeasurement/{enabled}"},
    {"method": "PUT", "path": "/api/resource/{id}"},
    {"method": "PUT", "path": "/api/rfid/{id}"},
    {"method": "PUT", "path": "/api/rfid/{id}/grit-track/{enable}"},
    {"method": "PUT", "path": "/api/rfid/{id}/mode/{mode}"},
    {"method": "PUT", "path": "/api/rfid/{id}/state/{onOff}"},
    {"method": "PUT", "path": "/api/scanner/{id}"},
    {"method": "PUT", "path": "/api/scanner/{id}/mode/{mode}"},
    {"method": "PUT", "path": "/api/solenoid/{id}"},
    {"method": "PUT", "path": "/api/solenoid/{id}/state/{onOff}"},
    {"method": "PUT", "path": "/api/trigger/{id}"},
    {"method": "PUT", "path": "/api/trigger/{id}/calibrate"},
    {"method": "PUT", "path": "/api/trigger/{id}/gate/{gateId}"},
    {"method": "PUT", "path": "/api/trigger/{id}/gritlock/{enabled}"},
    {"method": "PUT", "path": "/api/trigger/{id}/realtimepower/{enabled}"},
    {"method": "PUT", "path": "/api/trigger/{id}/refresh"},
    {"method": "PUT", "path": "/api/wallet/image/{type}"},
    {"method": "PUT", "path": "/api/wiegand-format/{id}"},
    {"method": "PUT", "path": "/api/wireguard/client/{name}/disable"},
    {"method": "PUT", "path": "/api/wireguard/client/{name}/enable"},
    {"method": "PUT", "path": "/api/xtndr/{id}"},
]
